### ISSUE TITLE
C:JET addition

### ISSUE THREAD

**Issue by amasson99** [amasson99/JEA-website#1]
http://jea.org/wp/home/for-educators/cjet/

At the bottom of the page under Magazines, add  
Volume 51 
2017-2018

Insert the attached copy, covers and cover credits using the same format as Vol. 50.

Also, go to each of the other volumes and check the Curriculum links. Some are not working. I suggest linking to the curriculum login area https://curriculum.jea.org/wp/ since it is a members-only area.

Thanks.

Connie Fulkerson, CJE 
JEA Administrative Assistant 
785-532-5532 
cfulker@ksu.edu 

![51_1 cjet cover 1](https://user-images.githubusercontent.com/26678640/42631184-0442fb7c-859f-11e8-8595-38918d7613be.jpg)
![51_1 cjet cover](https://user-images.githubusercontent.com/26678640/42631185-045857e2-859f-11e8-8b6f-84b54cd1afe5.jpg)
![51_2 coverw17](https://user-images.githubusercontent.com/26678640/42631186-046e484a-859f-11e8-9e19-3d698b504061.jpg)
![51_3 sp18_cover 1](https://user-images.githubusercontent.com/26678640/42631187-04834e48-859f-11e8-9e99-6addc582d0ee.jpg)
![51_3 sp18_cover](https://user-images.githubusercontent.com/26678640/42631188-04986120-859f-11e8-838f-da11eaf02ca8.jpg)
![51_4_su18_cjet](https://user-images.githubusercontent.com/26678640/42631189-04aea836-859f-11e8-9125-14e98dd4c46f.jpg)

**Comment by amasson99** [comment]
[CJET copy for web.txt](https://github.com/amasson99/JEA-website/files/2203982/CJET.copy.for.web.txt)
[Vol 51 cover credits for web.txt](https://github.com/amasson99/JEA-website/files/2203983/Vol.51.cover.credits.for.web.txt)

**Comment by amasson99** [comment]
@KateJEA @connieJEA I have made a draft, visible here: http://jea.org/wp/wp-admin/post.php?post=14594&action=edit

Let me know what needs to be changed

**Comment by KateJEA** [comment]
Has that page already been created?  If so, what's the URL?

**Comment by amasson99** [comment]
Here you go: http://jea.org/wp/cjet-stories/

**Comment by KateJEA** [comment]
Okay, the account is set up, and I emailed him with the login info.

**Comment by amasson99** [comment]
@KateJEA Can we close this issue? Not sure what else there is to do

**Comment by KateJEA** [comment]
Yep, I think we’re good on this.


~kld
