### ISSUE TITLE
Create a amasson@jea.org email account

### ISSUE THREAD

**Issue by amasson99** [amasson99/JEA-website#16]
When possible, lets get a amasson@jea.org email setup so I dont have people submitting tickets to my personal email.

**Comment by KateJEA** [comment]
Done.  pwd: ZYKU8Yw2; connection info in the screenshot below.

![screen shot 2018-07-27 at 1 42 32 pm](https://user-images.githubusercontent.com/37594598/43340802-1b6c6882-91a3-11e8-8fd9-deb8bea96b1d.png)

**Comment by amasson99** [comment]
@KateJEA Kelly might have talked to you about this, but can you also make a support@jea.org that forwards to that account? That way, in the future we wont have to make massive changes to get people to submit tickets?

**Comment by amasson99** [comment]
@KateJEA Is this a google account?

**Comment by KateJEA** [comment]
Yes, he did mention it.  I just created the "support@jea.org" forwarder.  Our email is still serviced through our web hosting, but George is migrating it all to google soon.

**Comment by amasson99** [comment]
Okay, sounds good. Can you point me in the direction of where to login?

**Comment by KateJEA** [comment]
Have you got an email client you're using, or do you want webmail?

**Comment by amasson99** [comment]
Webmail please

**Comment by KateJEA** [comment]
Go to jea.org/webmail, login with your complete email address and your password, then you'll have 3 email programs to choose from.

**Comment by amasson99** [comment]
Sounds good, thanks kate
