### ISSUE TITLE
Post Future Teacher news release

### ISSUE THREAD

**Issue by JEAConnie** [amasson99/JEA-website#17]
Please set this news release to be posted at 10 a.m. Aug. 17. There are no photos. Thanks.
[FutureTeacherScholarships2018_WEB.txt](https://github.com/amasson99/JEA-website/files/2232598/FutureTeacherScholarships2018_WEB.txt)

**Comment by JEAConnie** [comment]
Please set to release Future Teacher on Aug. 3 instead of Aug. 17. Thanks.

**Comment by amasson99** [comment]
Okay, ive made the draft of the post here: http://jea.org/wp/wp-admin/post.php?post=14613&action=edit

Also set the featured image as the jea awards stock photo

@JEAConnie

**Comment by JEAConnie** [comment]
Thanks.

Connie Fulkerson, CJE
JEA Administrative Assistant
cfulker@ksu.edu<mailto:cfulker@ksu.edu>
785-532-5532




On Jul 27, 2018, at 1:00 PM, Alex Masson <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, ive made the draft of the post here: http://jea.org/wp/wp-admin/post.php?post=14613&action=edit

Also set the featured image as the jea awards stock photo

@JEAConnie<https://github.com/JEAConnie>

**Comment by amasson99** [comment]
@JEAConnie Is it good to publish?

**Comment by JEAConnie** [comment]
Yes, on Aug. 3.

Connie Fulkerson, CJE
JEA Administrative Assistant
cfulker@ksu.edu<mailto:cfulker@ksu.edu>
785-532-5532




On Jul 27, 2018, at 3:16 PM, Alex Masson <notifications@github.com<mailto:notifications@github.com>> wrote:


@JEAConnie<https://github.com/JEAConnie> Is it good to publish?
