### ISSUE TITLE
Content for LINK page

### ISSUE THREAD

**Issue by klgdigital26** [amasson99/JEA-website#18]
Link image: I've linked an image (as a .jpg) to use somewhere at the top of the page. Please let me know if you need it in any other format.

Use this headline at the top of the page
JEA launches Link!

Use this text as intro copy after the headline
The Journalism Education Association is proud to unveil its latest member initiative – Link!

Link connects you directly to the JEA universe through personal one-on-one contact and support. Based on voluntary participation, Link matches new registrants (or those in need of a refresher) with a veteran JEA member to provide relevant and timely guidance. If you’d like help navigating all that JEA has to offer, click here to be matched with a veteran JEA member.

Link’s purpose is to provide positive member outreach regardless of geography, experience or program type.

The beauty of Link is its flexibility. Once a day. Once a week. Once a month. You decide. Once you have been matched with a Link volunteer, you can both work out how often you want to connect.

Sound intriguing?  

We encourage you to review the slideshow on this page to see if Link is right for you.

Have more questions, feel free to email me, Michael Malcom-Bjorklund, directly at mwbjorklund@outlook.com.

Sign up here to take advantage of Link today.

Use this text" followed by "This link"
Volunteer to Serve as a JEA Link 
https://goo.gl/forms/NtgaiVkrGGqK7X812

Use this text" and follow it with "This link"
Sign Up to Receive a JEA Link
https://goo.gl/forms/3VAwvg9moVoJEWig2

Place "this contact information" at the bottom. 
For more information, please contact me at:
Michael Malcom-Bjorklund, CJE
mwbjorklund@outlook.com

Conclude the page with the attached slideshow (if possible)
I've attached it as a .pdf.

It sounds like the launch of Link has been delayed. Please let me know when the items are placed on the site or if there are any other questions.

As always, I'm appreciative of the help,

Mike Malcom-Bjorklund

**Comment by amasson99** [comment]
@KateJEA @klgdigital26 Here is the page for Link: http://jea.org/wp/jea-launches-link/

Kate, do you guys have a pdf viewer installed on the website? It would help with the bottom pdf I linked.

**Comment by KateJEA** [comment]
I get "page not found".  Browsers are capable of viewing PDFs without any special web programming.  I usually just add a "target='_blank'" inside the a tag, so it will open in a separate tab.

**Comment by amasson99** [comment]
Sarah and kelly decided to do away with the pdf, this ticket is done now
