### ISSUE TITLE
Fwd: AAJA Accepting Applications for Executive Director

### ISSUE THREAD

**Issue by amasson99** [amasson99/JEA-website#2]
Here’s a job announcement for our Job Announcements page:

http://jea.org/wp/home/for-educators/job-announcements/

Thanks,

Kate Dubiel
Web Developer
Journalism Education Association
105 Kedzie Hall
828 Mid-Campus Dr S
Manhattan, KS  66506-1505
kated@jea.org

Hi Kelly,

 
My name is Patricia and I’m with the Asian American Journalists Association (AAJA) National office. As you may have recently heard, Kathy Chow is resigning from the position of AAJA Executive Director after eight years of leadership. AAJA is now kicking off a search for an ED who will work with the National staff at our office in San Francisco. I’ve copied in Yvonne Leow, AAJA’s National President. Feel free to reach out to her if you have any questions.

 
The application deadline is June 1, 2018 at 5pm PT. We appreciate if you could share this opportunity with any potential candidates in your network.

 
Job description: https://www.aaja.org/apply_to_be_aaja_executive_director

 
Best,

**Comment by amasson99** [comment]
@KateJEA Looks like this has already passed. Should I still post it?

**Comment by KateJEA** [comment]
Looks like they’re accepting applications until August 3, so go ahead and post it.

https://www.aaja.org/apply_to_be_aaja_executive_director <https://www.aaja.org/apply_to_be_aaja_executive_director>


Thanks,

Kate Dubiel
Web Developer
Journalism Education Association
105 Kedzie Hall
828 Mid-Campus Dr S
Manhattan, KS  66506-1505
kated@jea.org

**Comment by amasson99** [comment]
Okay, I have updated the content and can be seen here: http://jea.org/wp/home/for-educators/job-announcements/

**Comment by KateJEA** [comment]
Looks good, thanks!


~kld
