### ISSUE TITLE
In-page menus in the certification section

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#20]
Alex,

This is something that’s been missing since the theme change in the in-page menus in the certification section.  Their application deadline is approaching and they need the information on this page.

Plus, all the menus in that section need to be converted to the generated menus that we originally had for that section.  If you just do that, it should also straighten out Pam’s issue.

So just take all those static markup menus from those pages, and use the menu shortcode to insert the Wordpress menus we created for those pages - “Certification_CJE”, “Certification_MJE” and “Certification_Commission” - these go on all the pages in the certification section.  (That’s the page titled “Certification” and all the child pages of it.)

~kld

------------------------------------------------------------------------------------
Begin forwarded message:

From: Pamela Boller <pboller@ksu.edu>
Subject: FW: MJE FAQs on jea.org
Date: August 9, 2018 at 1:31:14 PM CDT
To: Kate Dubiel <kated@jea.org>

Is this fixed??
We have a September 1 deadline for certification applications for testing in Chicago and being recognized in Chicago.
Thank you.
 
Pam Boller
Journalism Education Association
105 Kedzie Hall
828 Mid Campus Dr S
Manhattan KS 66506
pboller@ksu.edu
staff@jea.org
Phone 785-532-5532
Fax 785-532-5563
 
From: Kim Green <kgreenmje@gmail.com>
Date: Friday, August 3, 2018 at 11:09 AM
To: Pamela Boller <pboller@ksu.edu>
Subject: MJE FAQs on jea.org
 
Hi, Pam-- 
I directed a potential MJE candidate to the FAQs for the MJE at jea.org. That information is no longer available. The rubric is there, but there once were sample responses as well as other information about the exam that are no longer available. Can we have the MJE FAQs back? The rubric can go with that information. The current FAQs tab is for the CJE only, but it shows up as a selection when the user selects Master Journalism Educator. MJE FAQs should go there. 
Thanks!
Kim
 
-- 
Kim Green, MJE
Chair, JEA Certification Committee

**Comment by KateJEA** [comment]
@amasson99, are you going to be able to work on this soon?  It's becoming urgent.

**Comment by amasson99** [comment]
@KateJEA Yes, I will work on this this afternoon.

**Comment by amasson99** [comment]
@KateJEA Just making sure I have this right, I need to delete the handmade menus, add the shortcode to the parent page, and then add the shortcodes to all of the child pages as well?

**Comment by amasson99** [comment]
@KateJEA And the child pages are just the ones that are linked in the shortcode menus, right?

**Comment by KateJEA** [comment]
@amasson99   Right.

You can confirm the list of child pages by searching the page list for "certification", and you'll see there which pages are child pages of the main certification page.

**Comment by amasson99** [comment]
Hey Kate, ive plugged the menus in for all of the certification related pages I could find, let me know if I missed any so we can close this ticket.

**Comment by amasson99** [comment]
@KateJEA

**Comment by KateJEA** [comment]
@amasson99  I checked this over and it looks right.  I asked Pam to also lay some eyes on it, since she's the Certification coordinator and more familiar with the content in that section.  Meanwhile, I went ahead and closed the ticket.  If Pam finds anything further we need to follow up on, I'll just open a new one.

Thanks!
