### ISSUE TITLE
Rising Stars press release

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#22]
@amasson99 :

Please post and schedule this to go live on Wednesday, August 22, 10:00 am.

There may be image content to go with this.  If so, I'll add it to this ticket later.

[Rising Stars.docx](https://github.com/amasson99/JEA-website/files/2298819/Rising.Stars.docx)

Thanks!

**Comment by KateJEA** [comment]
@amasson99 :
When you get this scheduled, please send the URL of the post to Karen Slusher (kslusher@cherrycreekschools.org) and Evelyn Lauer (elauer4@gmail.com).

**Comment by amasson99** [comment]
@KateJEA http://jea.org/wp/wp-admin/post.php?post=14705&action=edit

Let me know if its ready to be scheduled and sent out!

**Comment by KateJEA** [comment]
@amasson99  Looks good, go ahead and schedule it.

**Comment by KateJEA** [comment]
Thanks!
