### ISSUE TITLE
Medals of Merit press release

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#23]
@amasson99 :

Please post and schedule this to go live on Thursday, August 23, 10:00am.

Like the others, I'm waiting to hear back on image content to go with these.

[Medal of Merit.docx](https://github.com/amasson99/JEA-website/files/2298815/Medal.of.Merit.docx)

Thanks!

**Comment by KateJEA** [comment]
@amasson99 :
When you get this scheduled, please send the URL of the post to Karen Slusher (kslusher@cherrycreekschools.org) and Evelyn Lauer (elauer4@gmail.com).

**Comment by amasson99** [comment]
@KateJEA Okay, here is the preview: http://jea.org/wp/wp-admin/post.php?post=14708&action=edit

Let me know if its ready to be scheduled and sent out

**Comment by KateJEA** [comment]
@amasson99  Looks good, go ahead and schedule it.

**Comment by KateJEA** [comment]
Thanks!
