### ISSUE TITLE
Carl Towley Award press release

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#24]
@amasson99 :

Please post and schedule this to go live on Friday, August 24, 10:00 am.

There may also be images for this one.

[Carl Towley.docx](https://github.com/amasson99/JEA-website/files/2298833/Carl.Towley.docx)

Thanks!

**Comment by KateJEA** [comment]
@amasson99 :
When you get this scheduled, please send the URL of the post to Karen Slusher (kslusher@cherrycreekschools.org) and Evelyn Lauer (elauer4@gmail.com).

**Comment by amasson99** [comment]
@KateJEA Like the others, here is the link to the draft: http://jea.org/wp/wp-admin/post.php?post=14710&action=edit

Let me know if its ready to be sent out and scheduled

**Comment by KateJEA** [comment]
@amasson99   Can you remove the extra line returns in this, then go ahead and schedule it.

Thanks!

**Comment by KateJEA** [comment]
Thanks!
