### ISSUE TITLE
New job opening for our job announcements page

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#26]
@amasson99 
Here's a new job opening to add to our Job Announcements page.
http://jea.org/wp/home/for-educators/job-announcements/

Here's the URL to the full description:
https://sjobs.brassring.com/TGnewUI/Search/Home/Home?partnerid=25620&siteid=5494#jobDetails=3582935_5494

Also, could you please go through and remove any of the job openings that have been filled.  It's usually pretty easy to tell, just by clicking on their View More links.

**Comment by amasson99** [comment]
Made the post, also deleted the filled positions (basically all of them)
