### ISSUE TITLE
Certification FAQ updates

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#27]
@amasson99  The [Certification FAQ page](http://jea.org/wp/certification/faqs/) needs the edits requested in the attached file. 

[Updates-Edits to MJE FAQS USE.docx](https://github.com/amasson99/JEA-website/files/2324911/Updates-Edits.to.MJE.FAQS.USE.docx)

Thanks.

**Comment by amasson99** [comment]
I have made the updates
