### ISSUE TITLE
Corrections for Administrator of the Year press release

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#28]
@amasson99 
From Karen:
"I promise it is not my intention to have this be standard practice. Tracy Sena asked if I could make a change to the AOY release. I am attaching a copy of the new release. If you can replace the previous version, I would appreciate it."

[AOY.docx](https://github.com/amasson99/JEA-website/files/2329450/AOY.docx)

Please do this as soon as possible.  Thanks.

**Comment by amasson99** [comment]
Made the update
