### ISSUE TITLE
Contact form on front page needs captcha

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#29]
@amasson99 :
Spammers are hitting our front page contact form very heavily.  I suspect this has gone on for some time, but our old email service provider was blocking the spam emails coming to staff@jea.org.  GMail is not blocking them, and our staff inbox is getting flooded with spam.

Please address this as soon as possible.

I suggest removing the contact form (provided by the theme?) and replace it with a contact form created with one of the existing form plugins we have.  They have support for CAPTCHA, whereas the default contact form does not.  Also, investigate how we can evoke Akismet to prevent form spam.

**Comment by KateJEA** [comment]
@amasson99 @klgdigital26 
Any updates on this?  We're getting hundreds of junk mails a day in our staff inbox, and we can't filter these without also filtering legitimate messages sent to us.

**Comment by amasson99** [comment]
@KateJEA Hey Kate,

Just removed the contact form for the time being, Ill start working on replacing it with one of our own

**Comment by amasson99** [comment]
@KateJEA 

Hey Kate,

Just added the recaptcha form to the contact form and sent a test message.

Let me know if it cuts down on spam. If it does, feel free to close this ticket.

Thanks,

Alex

**Comment by KateJEA** [comment]
@amasson99 
Much better.  Now, we only just get "normal" spam.  Heheh!  Thanks.
