### ISSUE TITLE
Past winners of middle school media contest

### ISSUE THREAD

**Issue by amasson99** [amasson99/JEA-website#3]
I noticed the lists of past middle school winners are missing on the new website. Can you please restore them? Thanks.

Connie Fulkerson, CJE
JEA Administrative Assistant
cfulker@ksu.edu
785-532-5532

**Comment by amasson99** [comment]
@KateJEA Im not sure where this would be on the new website, can you help me out?

**Comment by KateJEA** [comment]
Sure.

Create a new page similar to this one:
http://jea.org/wp/home/awards-honors/junior-highmiddle-school-national-media-contest/spring-2017-middle-school-contest-results/ <http://jea.org/wp/home/awards-honors/junior-highmiddle-school-national-media-contest/spring-2017-middle-school-contest-results/>


Make its parent this one:
http://jea.org/wp/home/awards-honors/junior-highmiddle-school-national-media-contest/ <http://jea.org/wp/home/awards-honors/junior-highmiddle-school-national-media-contest/>


In the Wordpress dashboard, go to Appearance -> Menus, select the JHMS menu, and add your new page at the bottom of that menu, and save it.  Links to the new page should then appear in the in-page navigation on all the middle school contest pages.


That should do it.



~kld

**Comment by amasson99** [comment]
Cool, looks like 2018 was already made and just need to be added to the menu. 

Viewable here: http://jea.org/wp/wp-admin/nav-menus.php?action=edit&menu=101
