### ISSUE TITLE
Update a link

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#36]
@amasson99 
Here's a link that needs to be updated.  It's on this page:
[http://jea.org/wp/home/awards-honors/journalist-of-the-year/journalist-of-the-year-winners/]

----------------------------------------
Hi Kate!
Below is an email from one of our past Journalist of the Year winners. She has moved her website/portfolio to a different place and wanted to update the link with us so everyone can still find her work. Please let me know if you need anything else from me.
Thank you!
Rebecca

---------- Forwarded message ---------
From: meghan bobrowsky <meghanbobrowsky@gmail.com>
Date: Mon, Sep 24, 2018 at 12:44 PM
Subject: I moved my website to a new domain!
To: Rebecca Pollard <rebecca_pollard@lovejoyisd.net>, Pollard, Rebecca <PollardR@friscoisd.org>

Hi Rebecca,

Hope you're doing well. I'm updating my website with current work, but I wanted to keep my website from high school so you can use it as an example for future JOY applicants if you want. I moved the website from meghanbobrowsky.com to meghanbobrowsky.wordpress.com. I'll also link to it on my new website. 

Thanks,
Meghan

**Comment by amasson99** [comment]
The link has been updated
