### ISSUE TITLE
Update Scholastic Journalism Week page

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#38]
@amasson99 
This needs to be update by the end of the week.  The url to the page needing to be updated is included below.  The page should contain the content Adam send us below the dotted line.

Thanks!

From: Adam Dawkins <aadawkins@regisjesuit.com>
Date: October 1, 2018 at 10:01:06 AM CDT
To: Connie Fulkerson <cfulker@ksu.edu>
Cc: Evelyn Lauer <evelau@d219.org>
Subject: Changes to Scholastic Journalism Week Page 

Hi Connie! Hope all is well. 

We are ready to change the linked page below. Please replace the existing information with the following information and move it to the top fo the page. Thanks so much! - Adam  

http://jea.org/wp/home/news-events/scholastic-journalism-week/scholastic-journalism-week-logo-design-contest/

-------------------------------------------------------------

2018-2019
 Scholastic Journalism Week Design Contest 

Guidelines
 for Submission

Using
 the theme “Dedicated to Our Communities,” create a design for us to use for 2019 Scholastic Journalism Week promotional materials and on social media. The winning logo and designer will be revealed Saturday, Nov. 3, 2018, at the JEA/NSPA National High School
 Journalism Convention in Chicago. The winner need not be present to win. Judges will decide on the winning design after all entries, including those from the convention write-off contest, have been received. 

This
 year’s theme, “Dedicated to Our Communities,” focuses on reporting and publication that has revealed  there is more to the story, uncovered previously unknown truths, and helped the audience navigate in-depth information.

Create
 your design package with the theme in mind.

Guidelines
 for submission

Include
 the event title: Scholastic Journalism Week “Dedicated to Our Communities.”

Include
 the event date: Feb. 18-24, 2019 

Include
 a banner version, full Instagram-style square version, and a thumbnail version of your design.

Target
 market: Schools with journalism programs

Color
 required: Full color but logo must also work in B&W

Submit
 a Vector logo (Adobe Illustrator, InDesign, etc.)

Also
 submit your designs in JPEG and PDF format

Provide
 a datasheet (specifying fonts and Pantone colors)

Include
 a short rationale with the thinking behind your logo

Include
 your name, school name, your publication, your grade level, email address and phone number. Also include your personal and your piublication  Twitter and Instagram handles if you have them so we can promote your entry!

Deadline:
 Friday, Oct. 26, 2018

Submit
 your entries to: scholasticjournalismweek@gmail.com

ADAM A. DAWKINS '98, CJE , M.A. 
Regis Jesuit High School
Student Media Adviser, RJ MEDIA 
Past President, Colorado Student Media Association 
@NationalJEA Coordinator -@ScholasticJWeek 
303-408-0596 | aadawkins@regisjesuit.com | @adamdawk on Twitter
AMDG

**Comment by amasson99** [comment]
Ive updated the page with new content, I assumed he wanted it to be a bulleted list.
