### ISSUE TITLE
More job announcements

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#39]
@amasson99 
Here are two more job announcements to post on 
http://jea.org/wp/home/for-educators/job-announcements/

Job 1: http://explore.msujobs.msstate.edu/cw/en-us/job/497779/assistant-professor

Job 2: http://explore.msujobs.msstate.edu/cw/en-us/job/497777/instructor

**Comment by amasson99** [comment]
The job openings have been posted
