### ISSUE TITLE
Meeting Agenda

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#44]
@amasson99 @klgdigital26 
This needs to be posted on the website News area [as soon as possible, but no later than Monday]. Please match the formatting in the PDF so it shows up that way on the text (Roman numerals, tabs, etc.)

Thanks.

Connie Fulkerson, CJE
JEA Administrative Assistant
cfulker@ksu.edu
785-532-5532

Agenda__General Mtg_Chicago 2018.pdf

**Comment by amasson99** [comment]
@KateJEA Hey kate, it looks like the pdf didnt get uploaded

**Comment by KateJEA** [comment]
@amasson99 
Sorry - try one of these, instead.

[Agenda__General Mtg_Chicago 2018.docx](https://github.com/amasson99/JEA-website/files/2502139/Agenda__General.Mtg_Chicago.2018.docx)

[Agenda__General Mtg_Chicago 2018.pdf](https://github.com/amasson99/JEA-website/files/2502140/Agenda__General.Mtg_Chicago.2018.pdf)

**Comment by KateJEA** [comment]
@amasson99 
Never mind, I went ahead and took care of this one.  Thanks for trying, anyway.  :-)
