### ISSUE TITLE
Meeting minutes

### ISSUE THREAD

**Issue by KateJEA** [amasson99/JEA-website#45]
@amasson99 
This needs to be posted no later than Monday.

These are the meeting minutes from the General Membership meeting and the Board of Directors meeting in Chicago.  Each is put into a separate post and links are added to the Reports page (http://jea.org/wp/home/about-jea/reports/).

[Chicago JEA Board Meeting Minutes.txt](https://github.com/amasson99/JEA-website/files/2562876/Chicago.JEA.Board.Meeting.Minutes.txt)

[Chicago JEA General Meeting Minutes.txt](https://github.com/amasson99/JEA-website/files/2562877/Chicago.JEA.General.Meeting.Minutes.txt)

**Comment by amasson99** [comment]
@KateJEA Okay, i will get this knocked out soon - before 2 p.m. at the latest

**Comment by amasson99** [comment]
Got everything posted and tied into the reports page, let me know if I need to change anything, otherwise we can close this ticket

**Comment by amasson99** [comment]
@KateJEA

**Comment by KateJEA** [comment]
@amasson99 
Thanks for getting that out there.  I'd like you to make a couple of minor changes.

1) For both the general membership meeting minutes and the board meeting minutes, please change the headline to read more the same way as this report:
http://jea.org/wp/blog/2016/12/01/minutes-nov-10-2016-board-directors-meeting/

2. Make the subtitles (the ones in all caps) bold.

Once those are done, you can go ahead and close these tickets.  Thanks!
