### ISSUE TITLE
Aspiring Young Journalist

### ISSUE THREAD

**Issue by amasson99** [amasson99/JEA-website#5]
http://jea.org/wp/students/

Aspiring Young Journalist is missing from the Student Awards section on the home page AWARDS AND CONTEST pull-down menu. 
You need to retrieve from the old site and link the section on how to apply, list of past recipients, etc.

Connie Fulkerson, CJE 
JEA Administrative Assistant 
cfulker@ksu.edu 
785-532-5532

**Comment by amasson99** [comment]
@KateJEA Can you get me the copy for aspiring young journalist and ill plug it in?

**Comment by amasson99** [comment]
Updated the content, can be seen here: http://jea.org/wp/students/

**Comment by KateJEA** [comment]
From Connie: "The first couple headers are all different sizes. They should be consistent."

**Comment by amasson99** [comment]
![capture](https://user-images.githubusercontent.com/26678640/43023834-d01f9636-8c31-11e8-8e0e-7e795f0ba2fe.PNG)
So these need to be the same size? @KateJEA

**Comment by KateJEA** [comment]
The headers need to be the same size.  I think if you just make them all mixed case rather than all caps, that should fix it.

**Comment by amasson99** [comment]
Ohhhhhhhhhhhhhhhhhh gotcha

**Comment by amasson99** [comment]
Fixed it - viewable here: http://jea.org/wp/students/

**Comment by amasson99** [comment]
@KateJEA All of the headers for all of the awards pages are all caps rather than mixed case, and its all hand typed to fit with the theme. Do you want me to go through and change them all to mixed case?

**Comment by KateJEA** [comment]
How many pages are we talking about?

**Comment by amasson99** [comment]
Looks like 3 to 4 pages, basically everything underneath the dropdown for `Awards and contests`

**Comment by KateJEA** [comment]
Okay, I've been scanning around on other pages, and it looks like those are the only pages with all-cap headings.  I'm going to ask you to retype them in mixed case, to make them consistent with the rest of the site.

Now, if we should decide we'd rather have them in all-caps after all, the best way to do that is using CSS.  For one thing, it's a lot less work to do it that way, and will ensure better consistency throughout the website.  And when we change themes again, we won't have to go through everything and retype them again.  Make sense?

**Comment by amasson99** [comment]
Sounds good with me, I'll make the changes now. Thanks!

**Comment by amasson99** [comment]
made the changes
