### ISSUE TITLE
Fwd: MultiView Outreach - Website Code Missing

### ISSUE THREAD

**Issue by amasson99** [amasson99/JEA-website#6]
See Frank’s question below...

Kate Dubiel
Web Developer
Journalism Education Association
105 Kedzie Hall
828 Mid-Campus Dr S
Manhattan, KS 66506-1505
kated@jea.org

> Begin forwarded message:
> 
> From: Frank Humada <fhumada@multiview.com>
> Subject: RE: MultiView Outreach - Website Code Missing
> Date: April 27, 2018 at 2:37:35 PM CDT
> To: Kate Dubiel <kated@jea.org>
> 
> Good afternoon, Kate.
> 
> Thanks again for helping out with this.
> 
> I noticed that the ad placement is back on the homepage, but is it possible for this code to be run-of site, so that the ad is on every page of the site?
> 
> I’ve attached the media kit as reference.
> 
> Please let me know when you have a moment. Thanks.
> 
> Frank Humada | VP, Association Partnerships
> O: 202-684-7162 C: 202-849-0950
> http://www.multiview.com <http://www.multiview.com/>
> 
> 
> 
> 
> From: Frank Humada 
> Sent: Thursday, April 26, 2018 3:42 PM
> To: Kate Dubiel <kated@jea.org <kated@jea.org>>
> Subject: RE: MultiView Outreach - Website Code Missing
> 
> Thanks Kate!
> 
> I appreciate it!
> 
> Frank Humada | VP, Association Partnerships
> O: 202-684-7162 C: 202-849-0950
> http://www.multiview.com <http://www.multiview.com/>
> 
> 
> 
> 
> From: Kate Dubiel kated@jea.org <mailto:kated@jea.org> 
> Sent: Thursday, April 26, 2018 3:40 PM
> To: Frank Humada <fhumada@multiview.com <fhumada@multiview.com>>
> Subject: Re: MultiView Outreach - Website Code Missing
> 
> Frank - Alex says he’s working on it right now, so it should be running again sometime today.
> 
> 
> Thanks,
> 
> Kate Dubiel
> Web Developer
> Journalism Education Association
> 105 Kedzie Hall
> 828 Mid-Campus Dr S
> Manhattan, KS 66506-1505
> kated@jea.org <kated@jea.org>
> On Apr 24, 2018, at 8:46 AM, Frank Humada <fhumada@multiview.com <fhumada@multiview.com>> wrote:
> 
> Good morning, Kate.
> 
> I’ve just received a request from the AdOps team seeking an update for the implementation of the website code.
> 
> Please let me know if you had a moment to speak to your Exec about the placement, when you have a moment.
> 
> Thanks again for your help with this.
> 
> Frank Humada | VP, Association Partnerships
> O: 202-684-7162 C: 202-849-0950
> http://www.multiview.com <http://www.multiview.com/>
> <image003.jpg>
> 
> 
> 
> From: Kate Dubiel kated@jea.org <mailto:kated@jea.org> 
> Sent: Thursday, April 19, 2018 12:08 PM
> To: Frank Humada <fhumada@multiview.com <fhumada@multiview.com>>
> Subject: Re: MultiView Outreach - Website Code Missing
> 
> OOPS! Thanks for catching that. When we changed our website to a new theme, we forgot all about the ads. I’ll get that taken care of as soon as I can get with our Exec to find out where he wants the ads to go.
> 
> 
> Thanks,
> 
> Kate Dubiel
> Web Developer
> Journalism Education Association
> 105 Kedzie Hall
> 828 Mid-Campus Dr S
> Manhattan, KS 66506-1505
> kated@jea.org <kated@jea.org>
> 
> 
> On Apr 19, 2018, at 9:36 AM, Frank Humada <fhumada@multiview.com <fhumada@multiview.com>> wrote:
> 
> Kate,
> 
> I hope you are having a great week. 
> 
> I received a request from our AdOps team to reach out, as the website ad that we are selling on behalf of JEA on the JEA website is missing.
> 
> I’ve attached the media kit to show the placement, along with the code for the ad.
> 
> Would it be possible for this to be implemented back on the site? If any assistance is needed, provided access, we can have someone on our team place the code back on the site.
> 
> Please let me know when you have a moment. Thanks.
> 
> Frank Humada | VP, Association Partnerships
> O: 202-684-7162 C: 202-849-0950
> http://www.multiview.com <http://www.multiview.com/>
> <image003.jpg>
> 
> 
> 
> 
> 
> 
> 
> Notice: This message is the property of Multiview, Inc. and contains information that may be confidential and/or privileged. If you are not the intended recipient, you should not use, disclose or take any action based on this message. If you have received this transmission in error, please immediately contact the sender by return e-mail and delete this e-mail, and any attachments, from any computer. This email has been scanned for email related threats and delivered safely by Mimecast.
> For more information please visit http://www.mimecast.com <http://www.mimecast.com/>
> <728x90.txt><JEAweb_mediakitAUG17.pdf>
>

**Comment by amasson99** [comment]
![image001](https://user-images.githubusercontent.com/26678640/42631405-beec4366-859f-11e8-89d6-58b7c0233829.jpg)
![image004](https://user-images.githubusercontent.com/26678640/42631406-bf000f0e-859f-11e8-8529-9b2fc3fbd61c.jpg)
[Uploading JEAweb_mediakitAUG17.pdf…]()

**Comment by KateJEA** [comment]
I took care of this last week.
